FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

ARG TARGETOS TARGETARCH
RUN CGO_ENABLED=0 GOOS=linux go build -o loan-api ./cmd/api/main.go

RUN chmod +x loan-api

FROM alpine:latest
WORKDIR /app

COPY --from=builder /app/loan-api .

EXPOSE 8081

CMD ["./loan-api"]