FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

ARG TARGETOS TARGETARCH
RUN CGO_ENABLED=0 GOOS=linux go build -o loan-worker ./cmd/worker/main.go

RUN chmod +x loan-worker

FROM alpine:latest
WORKDIR /app

COPY --from=builder /app/loan-worker .

CMD ["./loan-worker"]